/* ============================================================
   UI strings — English / हिन्दी
   Content strings live in data/defaults.js (admin-editable).
   These are the fixed interface labels.
   ============================================================ */

export const ui = {
  en: {
    langName: 'English',
    langShort: 'EN',
    switchTo: 'हिन्दी में देखें',

    // nav
    navHome: 'Home',
    navAbout: 'About',
    navSectors: 'Sectors',
    navLeadership: 'Leadership',
    navContact: 'Contact',
    navOverview: 'Overview',
    navOfferings: 'What We Do',
    navTeam: 'People',
    navFaq: 'FAQ',
    backToGroup: 'InEra Group',
    menu: 'Menu',
    close: 'Close',

    // group home
    aGroupOf: 'A Group of',
    exploreSector: 'Enter',
    viewAll: 'View all',
    readMore: 'Read more',
    enterSite: 'Enter site',
    skipIntro: 'Skip',

    // sections
    sectionVision: 'Vision',
    sectionMission: 'Mission',
    sectionCharter: 'Governing Charter',
    sectionHistory: 'How it came about',
    sectionChairperson: "Chairperson's Note",
    sectionLeadership: 'Group Leadership',
    sectionOverview: 'Overview',
    sectionOfferings: 'What we do',
    sectionProcess: 'How we work',
    sectionPeople: 'People',
    sectionFaq: 'Questions',
    sectionContact: 'Contact',
    sectionAtAGlance: 'At a glance',

    // entity chrome
    partOfGroup: 'A brand trust of InEra Group',
    statusOperating: 'Operating',
    statusCommissioning: 'In commissioning',
    parentCompany: 'Parent company',
    sectorLabel: 'Sector',

    // forms
    formName: 'Full name',
    formEmail: 'Email address',
    formPhone: 'Phone',
    formOrg: 'Organisation',
    formSubject: 'Regarding',
    formMessage: 'Message',
    formSend: 'Send enquiry',
    formSending: 'Sending…',
    formSent: 'Received. We will reply to the email you gave us.',
    formError: 'Could not send. Please email us directly.',
    formRequired: 'Please fill in the required fields.',
    formSelectEntity: 'Which entity is this about?',
    formGeneral: 'InEra Group (general)',
    writeToUs: 'Write to us',
    callUs: 'Call',
    emailUs: 'Email',
    whatsapp: 'WhatsApp',
    officeHours: 'Office hours',
    location: 'Location',

    // AI
    aiTitle: 'InEra Assistant',
    aiSubtitle: 'Ask about the Group or any sector',
    aiPlaceholder: 'Ask a question…',
    aiGreeting:
      'I am the InEra Group assistant. Ask me about the Group, any of the four brand trusts, leadership, services or how to get in touch.',
    aiSuggest: 'Try asking',
    aiThinking: 'Looking through the site…',
    aiNoAnswer:
      'I could not find that on the site. Try rephrasing, or use the contact page and a person will answer you.',
    aiSources: 'From',
    aiOpen: 'Ask InEra',
    aiClear: 'Clear',
    aiSearchTitle: 'Search the site',
    aiSearchPlaceholder: 'Search pages, sectors, people, services…',
    aiSearchHint: 'Press Esc to close',
    aiSearchNone: 'Nothing matched.',
    aiSearchOpen: 'Search',
    aiDisclaimer: 'Answers are drawn only from this website’s own content.',
    aiAlsoLeads: 'Group leadership also includes',
    aiFourSectors: 'InEra Group holds four sector brand trusts',
    aiOwnedBy: 'All four are owned and administered by InEra Software Private Limited.',
    aiPerStudent: 'per student',
    aiMinBatch: 'minimum institutional batch',
    aiStudents: 'students',
    aiMainAreas: 'Main areas',
    aiQuoteLine:
      'quotes in writing for each engagement rather than publishing a fixed price list. Send the requirement and a written quote follows.',

    // misc
    backTop: 'Back to top',
    copyright: 'All rights reserved.',
    legalLine:
      'InEra Group is a brand and trademark of InEra Software Private Limited.',
    notFound: 'This page does not exist.',
    goHome: 'Go to the Group home page',
    loading: 'Loading…',
    savedLive: 'Published live',
    year: 'Year',

    // atlas / presence
    navAtlas: 'Atlas',
    navGallery: 'Gallery',
    navCareers: 'Careers',
    navNews: 'Highlights',
    navVerify: 'Verify',
    navAdmissions: 'Admissions',
    navPrivacy: 'Privacy',
    atlasTitle: 'Where we are',
    atlasHint: 'Drag to turn the globe · tap a city',
    atlasOffices: 'Offices',
    atlasHQ: 'Headquarters',
    atlasOffice: 'Office',
    atlasPartner: 'Partner location',
    atlasPresentHere: 'Present here',

    // gallery
    galleryAll: 'All',
    galleryEmpty: 'No pictures have been published yet.',
    galleryEmptyCategory: 'Nothing in this category yet.',

    // careers
    careersNone: 'No open roles at the moment. Write to us anyway if you think you belong here.',
    careersApply: 'Apply by email',

    // verification
    verifyTitle: 'Certificate verification',
    verifyIntro: 'Enter the certificate number exactly as printed on the document.',
    verifyPlaceholder: 'Certificate number',
    verifyAction: 'Verify',
    verifyFound: 'Verified — this certificate is on our register.',
    verifyNotFound: 'Not found.',
    verifyNotFoundBody: 'No certificate with that number is on our register. Check the number and try again, or write to us and we will look into it.',
    verifyName: 'Issued to',
    verifyNumber: 'Certificate number',
    verifyProgramme: 'Programme',
    verifyIssued: 'Issued on',
    verifyRemarks: 'Remarks',

    // admissions
    admissionsIndividual: 'Individual applicant',
    admissionsInstitution: 'Institution',
    admissionsTrack: 'Preferred track',
    admissionsCollege: 'College / institution',
    admissionsYear: 'Year of study',
    admissionsStudents: 'Approximate number of students',
    admissionsRole: 'Your role',
    admissionsSubmit: 'Submit application',
    admissionsSent: 'Application received. We will write to the email you gave us with the batch schedule.',
    admissionsClosed: 'Admissions are closed at the moment. Write to us to be told when the next batch opens.',

    // sections
    sectionValues: 'How we work',
    sectionReviews: 'What people say',
    sectionClients: 'Clients',
    sectionStudents: 'Participants',
    sectionHighlights: 'Latest',
    sectionPresence: 'Presence',
    printPage: 'Print this page',
  },

  hi: {
    langName: 'हिन्दी',
    langShort: 'हि',
    switchTo: 'View in English',

    navHome: 'मुख्य पृष्ठ',
    navAbout: 'परिचय',
    navSectors: 'क्षेत्र',
    navLeadership: 'नेतृत्व',
    navContact: 'संपर्क',
    navOverview: 'अवलोकन',
    navOfferings: 'हमारा कार्य',
    navTeam: 'सदस्य',
    navFaq: 'प्रश्न',
    backToGroup: 'इनएरा ग्रुप',
    menu: 'मेन्यू',
    close: 'बंद करें',

    aGroupOf: 'एक समूह —',
    exploreSector: 'प्रवेश',
    viewAll: 'सभी देखें',
    readMore: 'और पढ़ें',
    enterSite: 'साइट में प्रवेश',
    skipIntro: 'छोड़ें',

    sectionVision: 'दृष्टि',
    sectionMission: 'ध्येय',
    sectionCharter: 'शासन चार्टर',
    sectionHistory: 'यह कैसे बना',
    sectionChairperson: 'अध्यक्ष का संदेश',
    sectionLeadership: 'समूह नेतृत्व',
    sectionOverview: 'अवलोकन',
    sectionOfferings: 'हमारा कार्य',
    sectionProcess: 'कार्यप्रणाली',
    sectionPeople: 'सदस्य',
    sectionFaq: 'प्रश्न',
    sectionContact: 'संपर्क',
    sectionAtAGlance: 'एक दृष्टि में',

    partOfGroup: 'इनएरा ग्रुप का ब्रांड ट्रस्ट',
    statusOperating: 'संचालनरत',
    statusCommissioning: 'कमीशनिंग चरण में',
    parentCompany: 'मूल कंपनी',
    sectorLabel: 'क्षेत्र',

    formName: 'पूरा नाम',
    formEmail: 'ईमेल पता',
    formPhone: 'दूरभाष',
    formOrg: 'संस्था',
    formSubject: 'विषय',
    formMessage: 'संदेश',
    formSend: 'पूछताछ भेजें',
    formSending: 'भेजा जा रहा है…',
    formSent: 'प्राप्त हुआ। हम आपके दिए ईमेल पर उत्तर देंगे।',
    formError: 'भेजा नहीं जा सका। कृपया हमें सीधे ईमेल करें।',
    formRequired: 'कृपया आवश्यक फ़ील्ड भरें।',
    formSelectEntity: 'यह किस इकाई के बारे में है?',
    formGeneral: 'इनएरा ग्रुप (सामान्य)',
    writeToUs: 'हमें लिखें',
    callUs: 'दूरभाष',
    emailUs: 'ईमेल',
    whatsapp: 'व्हाट्सएप',
    officeHours: 'कार्यालय समय',
    location: 'स्थान',

    aiTitle: 'इनएरा सहायक',
    aiSubtitle: 'समूह या किसी भी क्षेत्र के बारे में पूछें',
    aiPlaceholder: 'प्रश्न पूछें…',
    aiGreeting:
      'मैं इनएरा ग्रुप सहायक हूँ। समूह, चारों ब्रांड ट्रस्ट, नेतृत्व, सेवाओं या संपर्क के बारे में पूछिए।',
    aiSuggest: 'यह पूछकर देखें',
    aiThinking: 'साइट में खोजा जा रहा है…',
    aiNoAnswer:
      'यह मुझे साइट पर नहीं मिला। कृपया प्रश्न दूसरे शब्दों में पूछें, या संपर्क पृष्ठ के माध्यम से लिखें।',
    aiSources: 'स्रोत',
    aiOpen: 'इनएरा से पूछें',
    aiClear: 'साफ़ करें',
    aiSearchTitle: 'साइट खोजें',
    aiSearchPlaceholder: 'पृष्ठ, क्षेत्र, सदस्य, सेवाएँ खोजें…',
    aiSearchHint: 'बंद करने हेतु Esc दबाएँ',
    aiSearchNone: 'कुछ नहीं मिला।',
    aiSearchOpen: 'खोज',
    aiDisclaimer: 'उत्तर केवल इसी वेबसाइट की सामग्री से लिए जाते हैं।',
    aiAlsoLeads: 'समूह नेतृत्व में इनके अतिरिक्त',
    aiFourSectors: 'इनएरा ग्रुप के चार क्षेत्रीय ब्रांड ट्रस्ट हैं',
    aiOwnedBy: 'चारों का स्वामित्व एवं प्रशासन इनएरा सॉफ़्टवेयर प्राइवेट लिमिटेड के पास है।',
    aiPerStudent: 'प्रति विद्यार्थी',
    aiMinBatch: 'न्यूनतम संस्थागत बैच',
    aiStudents: 'विद्यार्थी',
    aiMainAreas: 'मुख्य क्षेत्र',
    aiQuoteLine:
      'प्रत्येक कार्यादेश हेतु लिखित रूप में उद्धरण देता है; कोई निश्चित मूल्य-सूची प्रकाशित नहीं की जाती। आवश्यकता भेजिए, लिखित उद्धरण भेजा जाएगा।',

    backTop: 'ऊपर जाएँ',
    copyright: 'सर्वाधिकार सुरक्षित।',
    legalLine:
      'इनएरा ग्रुप, इनएरा सॉफ़्टवेयर प्राइवेट लिमिटेड का ब्रांड एवं ट्रेडमार्क है।',
    notFound: 'यह पृष्ठ उपलब्ध नहीं है।',
    goHome: 'समूह के मुख्य पृष्ठ पर जाएँ',
    loading: 'लोड हो रहा है…',
    savedLive: 'लाइव प्रकाशित',
    year: 'वर्ष',

    // atlas / presence
    navAtlas: 'एटलस',
    navGallery: 'गैलरी',
    navCareers: 'करियर',
    navNews: 'मुख्य समाचार',
    navVerify: 'सत्यापन',
    navAdmissions: 'प्रवेश',
    navPrivacy: 'गोपनीयता',
    atlasTitle: 'हम कहाँ हैं',
    atlasHint: 'ग्लोब घुमाने हेतु खींचें · शहर पर टैप करें',
    atlasOffices: 'कार्यालय',
    atlasHQ: 'मुख्यालय',
    atlasOffice: 'कार्यालय',
    atlasPartner: 'साझेदार स्थल',
    atlasPresentHere: 'यहाँ उपस्थित',

    // gallery
    galleryAll: 'सभी',
    galleryEmpty: 'अभी कोई चित्र प्रकाशित नहीं हुआ है।',
    galleryEmptyCategory: 'इस श्रेणी में अभी कुछ नहीं है।',

    // careers
    careersNone: 'इस समय कोई रिक्ति नहीं है। फिर भी यदि आप स्वयं को उपयुक्त मानते हैं तो हमें लिखिए।',
    careersApply: 'ईमेल द्वारा आवेदन',

    // verification
    verifyTitle: 'प्रमाणपत्र सत्यापन',
    verifyIntro: 'प्रमाणपत्र संख्या ठीक वैसे ही दर्ज करें जैसी दस्तावेज़ पर मुद्रित है।',
    verifyPlaceholder: 'प्रमाणपत्र संख्या',
    verifyAction: 'सत्यापित करें',
    verifyFound: 'सत्यापित — यह प्रमाणपत्र हमारे रजिस्टर में दर्ज है।',
    verifyNotFound: 'नहीं मिला।',
    verifyNotFoundBody: 'इस संख्या का कोई प्रमाणपत्र हमारे रजिस्टर में नहीं है। संख्या जाँचकर पुनः प्रयास करें, अथवा हमें लिखें।',
    verifyName: 'जारी किया गया',
    verifyNumber: 'प्रमाणपत्र संख्या',
    verifyProgramme: 'कार्यक्रम',
    verifyIssued: 'जारी तिथि',
    verifyRemarks: 'टिप्पणी',

    // admissions
    admissionsIndividual: 'व्यक्तिगत आवेदक',
    admissionsInstitution: 'संस्था',
    admissionsTrack: 'पसंदीदा ट्रैक',
    admissionsCollege: 'महाविद्यालय / संस्था',
    admissionsYear: 'अध्ययन वर्ष',
    admissionsStudents: 'विद्यार्थियों की अनुमानित संख्या',
    admissionsRole: 'आपकी भूमिका',
    admissionsSubmit: 'आवेदन भेजें',
    admissionsSent: 'आवेदन प्राप्त हुआ। बैच की समय-सारिणी आपके दिए ईमेल पर भेजी जाएगी।',
    admissionsClosed: 'इस समय प्रवेश बंद हैं। अगला बैच खुलने की सूचना हेतु हमें लिखें।',

    // sections
    sectionValues: 'हमारी कार्यशैली',
    sectionReviews: 'लोग क्या कहते हैं',
    sectionClients: 'ग्राहक',
    sectionStudents: 'प्रतिभागी',
    sectionHighlights: 'नवीनतम',
    sectionPresence: 'उपस्थिति',
    printPage: 'यह पृष्ठ प्रिंट करें',
  },
};

export default ui;
